version: '3'

services:
  db:
    restart: always
    image: kiasaki/alpine-postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      #      - PGDATA: /tmp
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:

#```
#$  docker exec -it tmp_postgres_1 psql -U foo baz
#```
